data:
  image: busybox:latest
  volumes:
    - ./www:/app
  entrypoint: top

fpm:
  build: ./php/php56
  volumes_from:
    - data
  expose:
    - 9000
  links:
    - mysql:mysql
    - mongo:mongo
    - memcached:memcached
    - redis:redis
  environment:
    XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

cli:
  build: ./php/php56
  volumes_from:
    - data
  working_dir: /app
  tty: true
  stdin_open: true
  command: '/bin/bash'
  tty: true
  links:
    - mysql:mysql
    - mongo:mongo
    - memcached:memcached
    - redis:redis

nginx:
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - ./www:/app
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/nginx
  links:
    - fpm
mysql:
  image: mysql:5.7
  volumes:
    - ./mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword

mongo:
  image: mongo
  ports:
    - "27017:27017"

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis
  ports:
    - "6379:6379"